const EXAM_DATA = [
  {
    id: 'teknik-resim',
    title: 'Teknik Resim',
    summary: '<b>Çizgi ve Yazı:</b> Teknik resimde sürekli kalın çizgi görünen kenarlar için, kesik orta çizgi ise görünmeyen kısımlar içindir. Standart yazılar 75 derece eğik olmalıdır. <br><br><b>Geometri ve Görünüş:</b> Alın (Ön), Profil (Yan) ve Yatay (Üst) düzlemlere bakış açısı çıkarılır. Ölçekler (1:2 küçültme, 2:1 büyütme) gerçek boyuta oranlar.',
    questions: [
      { q: "Teknik resimde kullanılan sürekli kalın çizgi nerede kullanılır?", a: "Görünen çevreler ve kenarlarda kullanılır." },
      { q: "Kesik orta kalınlıktaki çizginin (----) kullanım alanı nedir?", a: "Görünmeyen çevreler ve kenarlarda kullanılır." },
      { q: "Teknik resimde standart yazı tipinde harf ve rakamlar kaç derece eğik yazılmalıdır?", a: "75 derece eğik yazılmalıdır." },
      { q: "Teknik resimde kullanılan kalemlerden 'H' serisi ve 'B' serisi arasındaki fark nedir?", a: "H serisi sert (hard), B serisi yumuşak (black) kalemlerdir. İnce çizimler için 'H' uygundur." },
      { q: "Pergel ve cetvel kullanarak bir doğru parçası nasıl iki eşit parçaya bölünür?", a: "Doğru uçlarından yarıdan fazla açılan pergelle yaylar çizilir, kesişimler birleştirilir." },
      { q: "Bir çemberin içine düzgün altıgen çizimi için pergel açıklığı ne kadar olmalıdır?", a: "Pergel açıklığı, çemberin yarıçapı (r) kadar olmalıdır." },
      { q: "Ölçek nedir? 1:2 ölçeği ile 5:1 ölçeği arasındaki farkı açıklayınız.", a: "1:2 küçültme (yarı boy), 5:1 büyütme (5 kat) ölçeğidir." },
      { q: "Teknik resimde ön, yan ve üst görünüş hangi düzlemlere çizilir?", a: "Ön-Alın, Yan-Profil, Üst-Yatay düzleme çizilir." },
      { q: "Ölçülendirmede sınırlandırma çizgileri nasıl olmalıdır?", a: "İnce çizgilerle çizilmeli ve ölçü bağlama çizgisini 1-2 mm aşmalıdır." },
      { q: "T-Cetveli ve Gönyeler hangi amaçlarla kullanılır?", a: "T-Cetveli yatay çizgiler, Gönyeler dikey ve açılı (30,45,60) çizgiler için kullanılır." }
    ],
    flashcards: [
      { front: "Sürekli Kalın Çizgi", back: "Görünen kenarlar ve çevreler." },
      { front: "Kesik Orta Çizgi", back: "Görünmeyen kenarlar ve çevreler." },
      { front: "Noktalı İnce Çizgi", back: "Eksen çizgileri ve simetri merkezleri." },
      { front: "Yazı Eğimi", back: "75 derece eğik yazı standarttır." },
      { front: "H Kalem", back: "Sert uçlu, ince ve hassas çizimler içindir." },
      { front: "B Kalem", back: "Yumuşak uçlu, koyu ve sanatsal çizimler içindir." },
      { front: "1:1 Ölçek", back: "Gerçek boyutlu çizim demektir." },
      { front: "1:5 Ölçek", back: "Nesneyi 5 kat küçülterek çizmek demektir." },
      { front: "2:1 Ölçek", back: "Nesneyi 2 kat büyüterek çizmek demektir." },
      { front: "Alın Düzlemi", back: "Ön görünüşün çizildiği düşey düzlem." },
      { front: "Profil Düzlemi", back: "Yan görünüşün çizildiği yan düzlem." },
      { front: "İzometrik Projeksiyon", back: "30 derece açıyla çizilen 3 boyutlu görünüş." },
      { front: "Perspektif", back: "3B görüntüyü 2B düzlemde gösterme tekniği." },
      { front: "Eksantrik", back: "Merkezleri çakışmayan dairesel parçalar." },
      { front: "Tolerans", back: "Boyutlarda izin verilen hata payı." },
      { front: "Yüzey İşaretleri", back: "Pürüzlülük derecesini gösteren semboller." },
      { front: "Kesit Alma", back: "İç yapıyı görmek için yapılan hayali kesim." },
      { front: "Taramalar", back: "Kesit yüzeyleri gösteren ince paralel çizgiler." },
      { front: "Norm Yazı", back: "Teknik resimdeki standart yazı tipi." },
      { front: "Yatay Düzlem", back: "Üst görünüşün çizildiği yer düzlemi." }
    ]
  },
  {
    id: 'tinkercad',
    title: 'Tinkercad & 3D Tasarım',
    summary: '<b>Temel Araçlar:</b> Tinkercad bulut tabanlı bir 3D tasarım aracıdır. Hole (Delik) ve Group (Grupla) özellikleri ile karmaşık formlar oluşturulur. <br><br><b>Dosya Yönetimi:</b> Tasarımlar .STL (3D Yazıcı) veya .SVG (Vektör) olarak dışa aktarılabilir. Align (Hizala) ve Ruler (Cetvel) hassas yerleşim için kritiktir.',
    questions: [
      { q: "Tinkercad'de bir nesneyi diğerinden çıkarmak için hangi özellik kullanılır?", a: "Nesnenin şekil ayarlarından 'Hole' (Delik) özelliği seçilir." },
      { q: "'Group' komutu katı ve delik nesnelerle nasıl çalışır?", a: "Gruplandığında delik nesnesinin hacmi katı nesneden silinir." },
      { q: "Nesneleri hizalamak için hangi komut kullanılır?", a: "'Align' (Hizala) komutu (L kısayolu) kullanılır." },
      { q: "3D baskı için hangi dosya formatı tercih edilir?", a: "Genellikle '.STL' formatında dışa aktarma yapılır." },
      { q: "'Workplane' aracı ne amaçla kullanılır?", a: "Nesne yüzeylerinde çizim yapmak için yeni zemin oluşturur." },
      { q: "'Copy' ve 'Duplicate' arasındaki fark nedir?", a: "Duplicate (Ctrl+D) yapılan hareketleri hafızaya alır." },
      { q: "Döndürme işlemi nasıl yapılır?", a: "Nesne kenarlarındaki kavisli oklardan tutarak yapılır." },
      { q: "Hassas ölçüm için hangi araç kullanılır?", a: "'Ruler' (Cetvel) aracı kullanılır." },
      { q: "Dışarıdan 2D çizim almak için hangi format kullanılır?", a: "'.SVG' formatındaki dosyalar 'Import' edilebilir." },
      { q: "Gruplanmış nesne nasıl ayrılır?", a: "'Ungroup' (Grubu Çöz) komutuyla ayrılır." }
    ],
    flashcards: [
      { front: "Hole", back: "Nesneden parça çıkarmak için 'delik' özelliği." },
      { front: "Group", back: "Nesneleri kalıcı olarak birleştirme veya delme." },
      { front: "Align", back: "Nesneleri eksenlerde hizalama aracı." },
      { front: "STL", back: "3D yazıcılar için standart dosya formatı." },
      { front: "Workplane", back: "Yüzeylere çizim yapmayı sağlayan düzlem." },
      { front: "Duplicate", back: "Akıllı kopyalama (hareketleri tekrar eder)." },
      { front: "Ruler", back: "Hassas milimetrik ölçülendirme cetveli." },
      { front: "Import", back: "SVG veya STL gibi dış dosyaları alma." },
      { front: "Scribble", back: "Elle serbest çizimle 3D model oluşturma." },
      { front: "Snap Grid", back: "Izgara hassasiyeti (takılma aralığı)." },
      { front: "Shape Generators", back: "Topluluk yapımı karmaşık şekil araçları." },
      { front: "Lock Tool", back: "Nesneyi yanlışlıkla oynamasın diye sabitleme." },
      { front: "Hide Tool", back: "Kalabalığı engellemek için nesneyi gizleme." },
      { front: "Notes Tool", back: "Tasarım üzerine not bırakma aracı." },
      { front: "Minecraft Export", back: "Modeli Minecraft dünyasına aktarma." },
      { front: "Codeblocks", back: "Kod yazarak 3D tasarım yapma bölümü." },
      { front: "Cruising", back: "Nesnelerin birbirine temasını sağlayan mod." },
      { front: "SVG", back: "Tinkercad'in içe alabildiği 2B vektör formatı." },
      { front: "Export", back: "Tasarımı bilgisayara indirme işlemi." },
      { front: "Circuit Assembly", back: "Elektronik bileşenlerle tasarım yapma." }
    ]
  },
  {
    id: 'fusion-intro',
    title: 'Fusion 360 - Temel',
    summary: '<b>Sektörel Tasarım:</b> CAD (Tasarım), CAM (Üretim) ve CAE (Analiz) süreçlerini birleştiren profesyonel araçtır. Parametrik modelleme sayesinde bir ölçü değiştiğinde tüm yapı güncellenir. <br><br><b>Montaj:</b> Component (Bileşen) yapısı ve Joint (Eklem) tipleri (Rigid, Revolute) ile parçalar arası mekanik ilişkiler kurulur.',
    questions: [
      { q: "Parametrik modellemenin avantajı nedir?", a: "Ölçü değişince tüm modelin otomatik güncellenmesidir." },
      { q: "CAD ve CAM farkı nedir?", a: "CAD tasarım, CAM üretim (makine kodları) sürecidir." },
      { q: "Neden Component kullanılmalıdır?", a: "Bağımsız hareket ve montaj ilişkileri kurabilmek için." },
      { q: "Joint komutu ne işe yarar?", a: "Parçaları dinamik veya sabit şekilde birbirine bağlar." },
      { q: "Rigid ve Revolute farkı nedir?", a: "Rigid sabit tutar, Revolute dönme izni verir." },
      { q: "Timeline ne işe yarar?", a: "Geçmiş adımları görmeyi ve hataları düzeltmeyi sağlar." },
      { q: "3D yazıcı formatı nedir?", a: "En yaygın kullanılan '.STL' formatıdır." },
      { q: "Slicing nedir?", a: "Modeli katmanlara bölüp G-Code'a dönüştürmektir." },
      { q: "Yay yapmak için hangi komut kullanılır?", a: "'Coil' komutu kullanılır." },
      { q: "Browser bölümü ne işe yarar?", a: "Tasarımdaki tüm bileşen ve taslakları listeler." }
    ],
    flashcards: [
      { front: "CAD", back: "Bilgisayar Destekli Tasarım sürecidir." },
      { front: "CAM", back: "Bilgisayar Destekli Üretim sürecidir." },
      { front: "CAE", back: "Analiz, dayanıklılık ve mühendislik testleridir." },
      { front: "Parametrik Modelleme", back: "Ölçülere dayalı, esnek modelleme türü." },
      { front: "Component (Bileşen)", back: "Bağımsız ve montajlanabilir parçalar." },
      { front: "Rigid Joint", back: "Tamamen sabitleyen eklem tipidir." },
      { front: "Revolute Joint", back: "Tek eksende dönme izni veren eklem tipidir." },
      { front: "Slider Joint", back: "Hat boyunca kayma izni veren eklem tipidir." },
      { front: "STL Formatı", back: "Yazıcıya gönderilen standart yüzey formatı." },
      { front: "Dilimleme (Slicing)", back: "Modeli katman katman G-Code'a çevirme." },
      { front: "Timeline", back: "İşlem geçmişini gösteren zaman çizelgesi." },
      { front: "Browser", back: "Model hiyerarşisini gösteren kısım." },
      { front: "Extrude", back: "Yükseklik vererek katı oluşturma komutu." },
      { front: "Revolve", back: "Döndürerek katı oluşturma komutu." },
      { front: "Coil", back: "Yay veya vida dişi oluşturma komutu." },
      { front: "Fillet", back: "Keskin köşeleri yuvarlatma (kavis)." },
      { front: "Chamfer", back: "Köşelere eğik pah kırma işlemi." },
      { front: "Mirror", back: "Simetrik kopyalama aracı." },
      { front: "Combine", back: "Gövdeleri birleştirme veya çıkarma." },
      { front: "Shell", back: "İçini boşaltıp kabuk yapma komutu." }
    ]
  },
  {
    id: 'fusion-advanced',
    title: 'Fusion 360 - İleri',
    summary: '<b>Karmaşık Formlar:</b> Sweep (Yol boyu sür), Loft (Geçiş örme) ve Shell (Kabuk yap) gibi ileri komutlar kullanılır. <br><br><b>Analiz ve İşleme:</b> Rib (Dayanıklılık duvarı) ile yapılar güçlendirilir. Render aşamasında fotoğraf kalitesinde görüntüler alınırken, Simulation ile fiziksel dayanıklılık test edilir.',
    questions: [
      { q: "Joint komutu ne işe yarar?", a: "Bileşenleri bağlar ve hareket tanımlar." },
      { q: "Rigid ve Revolute farkı nedir?", a: "Biri tamamen sabit, diğeri dairesel hareketlidir." },
      { q: "Sweep için ne gereklidir?", a: "Bir Profil ve bir Yol (Path) gereklidir." },
      { q: "Loft ne zaman kullanılır?", a: "Farklı şekiller arasında yumuşak geçiş yapmak için." },
      { q: "Component neden önemlidir?", a: "Montaj ve simülasyon için şarttır." },
      { q: "Shell komutu ne yapar?", a: "Yüzeyi kaldırıp içini boşaltır, duvar payı bırakır." },
      { q: "Döner eklem hangisidir?", a: "'Revolute Joint' dairesel hareket sağlar." },
      { q: "Rib ne amaçla kullanılır?", a: "Dayanıklılığı artıran destek duvarları örer." },
      { q: "Motion Study nedir?", a: "Mekanizmanın hareketlerini test eden modüldür." },
      { q: "Combine 'Cut' ne yapar?", a: "Bir nesneyi diğerinden eksiltir." }
    ],
    flashcards: [
      { front: "Sweep", back: "Profilin bir yol boyunca sürülmesidir." },
      { front: "Loft", back: "İki farklı kesit arasında katı örme." },
      { front: "Shell", back: "Nesneyi boşaltıp kabuğa dönüştürme." },
      { front: "Fillet", back: "Köşeleri kavisli şekilde kırma." },
      { front: "Mirror", back: "Düzleme göre simetri kopyası alma." },
      { front: "Combine (Cut)", back: "Hacimsel çıkarma işlemi." },
      { front: "Rib (Payanda)", back: "Destekleyici ince duvar yapısı." },
      { front: "Circular Pattern", back: "Dairesel hat üzerinde çoğaltma." },
      { front: "Motion Study", back: "Canlı mekanizma hareket testi." },
      { front: "Slider Joint", back: "Kanal içinde kayma simülasyonu." },
      { front: "Thread", back: "Gerçekçi vida dişi açma komutu." },
      { front: "Spline", back: "Esnek ve eğrisel çizgiler çizme aracı." },
      { front: "Appearance", back: "Malzeme rengi ve dokusu (A kısayolu)." },
      { front: "Render", back: "Gerçekçi fotoğraf kalitesinde çıktı alma." },
      { front: "Simulation", back: "Fiziksel dayanıklılık testi modülü." },
      { front: "Generative Design", back: "Yapay zeka destekli form tasarımı." },
      { front: "Assembly", back: "Parçaların montajlanmış bütünü." },
      { front: "Parametric History", back: "Timeline ile değişen model yapısı." },
      { front: "Rectangular Pattern", back: "Izgara düzeninde (satır/sütun) çoğaltma." },
      { front: "Physical Material", back: "Nesneye gerçek ağırlık ve özellik atama." }
    ]
  }
];

window.EXAM_DATA = EXAM_DATA;
